import = ["~/.config/alacritty/rose_pine.toml"]

[font]

size = 12.0

[font.bold]

family = "Hack Nerd Font"


[font.bold_italic]

family = "Hack Nerd Font"


[font.italic]

family = "Hack Nerd Font"


[font.normal]

family = "Hack Nerd Font"

